services:
  vite-app:
    build: .
    container_name: vite-hot-reload
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
